name: av_solar_services
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  get: ^4.7.2
  get_storage: ^2.1.1  # Add version or remove if not used
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter_phone_direct_caller: ^2.1.0
  numberpicker: ^2.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  path_provider_android: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/avLogo.png
